language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.2
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.2
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.3
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.3
      env: COMPOSER_FLAG=--prefer-stable

before_script:
  # Composer
  - travis_retry composer install --no-interaction
  # Coverage
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" && "$COMPOSER_FLAG" == "" ]]; then COVERAGE=1; fi

script:
  # Quality Assurance
  - composer run-script qa-linter
  - composer run-script qa-codesniffer

  # CodeChecker
  - composer create-project nette/code-checker temp/code-checker dev-master --no-interaction
  - php temp/code-checker/src/code-checker.php --short-arrays

  # Nette\Tester
  - composer run-script qa-tester-info
  - composer run-script qa-tester

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
